<?php

return [

    'MALE' => 'MALE',
    'FEMALE' => 'FEMALE',
    'TRANSMALE' => 'TRANSGENDER MALE',
    'TRANSFEMALE' => 'TRANSGENDER FEMALE',
    'GENDERQUEER' => 'GENDERQUEER',
    'NONBINARY' => 'NONBINARY',
    'UNLISTED' => 'OTHER / UNLISTED',
    'NONE' => 'PREFER NOT TO ANSWER',

];
